pipeline {
    agent any

    tools {
        maven "M3"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/istamarahsan/blibli-bring-on-the-future-2024.git'
            }
        }
        stage ('Build') {
            steps {
                sh 'cd java-project && mvn clean package'
            }
            post {
                success {
                    archiveArtifacts 'java-project/target/*.jar'
                    archiveArtifacts 'java-project/target/bom.json'
                    dependencyTrackPublisher artifact: 'java-project/target/bom.xml', projectName: 'java-project', projectVersion: '1.0-SNAPSHOT', synchronous: true, projectProperties: [tags: ['level=build']]
                }
            }
        }
    }
}
